// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pkg/connection/pb/connection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetFor string `protobuf:"bytes,1,opt,name=setFor,proto3" json:"setFor,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SetOf  string `protobuf:"bytes,3,opt,name=setOf,proto3" json:"setOf,omitempty"`
}

func (x *SetInfo) Reset() {
	*x = SetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInfo) ProtoMessage() {}

func (x *SetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInfo.ProtoReflect.Descriptor instead.
func (*SetInfo) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{0}
}

func (x *SetInfo) GetSetFor() string {
	if x != nil {
		return x.SetFor
	}
	return ""
}

func (x *SetInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetInfo) GetSetOf() string {
	if x != nil {
		return x.SetOf
	}
	return ""
}

type GetSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *SetInfo `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *GetSetRequest) Reset() {
	*x = GetSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetRequest) ProtoMessage() {}

func (x *GetSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetRequest.ProtoReflect.Descriptor instead.
func (*GetSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{1}
}

func (x *GetSetRequest) GetSet() *SetInfo {
	if x != nil {
		return x.Set
	}
	return nil
}

type GetSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetSetResponse) Reset() {
	*x = GetSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetResponse) ProtoMessage() {}

func (x *GetSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetResponse.ProtoReflect.Descriptor instead.
func (*GetSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{2}
}

func (x *GetSetResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *SetInfo `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *DeleteSetRequest) Reset() {
	*x = DeleteSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetRequest) ProtoMessage() {}

func (x *DeleteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSetRequest) GetSet() *SetInfo {
	if x != nil {
		return x.Set
	}
	return nil
}

type DeleteSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteSetResponse) Reset() {
	*x = DeleteSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetResponse) ProtoMessage() {}

func (x *DeleteSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddToSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set   *SetInfo `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Items []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *AddToSetRequest) Reset() {
	*x = AddToSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToSetRequest) ProtoMessage() {}

func (x *AddToSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToSetRequest.ProtoReflect.Descriptor instead.
func (*AddToSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{5}
}

func (x *AddToSetRequest) GetSet() *SetInfo {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *AddToSetRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddToSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddToSetResponse) Reset() {
	*x = AddToSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToSetResponse) ProtoMessage() {}

func (x *AddToSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToSetResponse.ProtoReflect.Descriptor instead.
func (*AddToSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{6}
}

func (x *AddToSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveFromSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set   *SetInfo `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Items []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RemoveFromSetRequest) Reset() {
	*x = RemoveFromSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromSetRequest) ProtoMessage() {}

func (x *RemoveFromSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromSetRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveFromSetRequest) GetSet() *SetInfo {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *RemoveFromSetRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type RemoveFromSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RemoveFromSetResponse) Reset() {
	*x = RemoveFromSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_connection_pb_connection_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromSetResponse) ProtoMessage() {}

func (x *RemoveFromSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connection_pb_connection_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromSetResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_connection_pb_connection_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFromSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_connection_pb_connection_proto protoreflect.FileDescriptor

var file_pkg_connection_pb_connection_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x47, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x74, 0x46, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x74,
	0x46, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x4f, 0x66, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x65, 0x74, 0x4f, 0x66, 0x22, 0x36, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x73, 0x65,
	0x74, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x03, 0x73, 0x65, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x53, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x73, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xbc, 0x02, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x74, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x09, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f,
	0x53, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x64,
	0x64, 0x54, 0x6f, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x56, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65,
	0x74, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_connection_pb_connection_proto_rawDescOnce sync.Once
	file_pkg_connection_pb_connection_proto_rawDescData = file_pkg_connection_pb_connection_proto_rawDesc
)

func file_pkg_connection_pb_connection_proto_rawDescGZIP() []byte {
	file_pkg_connection_pb_connection_proto_rawDescOnce.Do(func() {
		file_pkg_connection_pb_connection_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_connection_pb_connection_proto_rawDescData)
	})
	return file_pkg_connection_pb_connection_proto_rawDescData
}

var file_pkg_connection_pb_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_connection_pb_connection_proto_goTypes = []interface{}{
	(*SetInfo)(nil),               // 0: connection.SetInfo
	(*GetSetRequest)(nil),         // 1: connection.GetSetRequest
	(*GetSetResponse)(nil),        // 2: connection.GetSetResponse
	(*DeleteSetRequest)(nil),      // 3: connection.DeleteSetRequest
	(*DeleteSetResponse)(nil),     // 4: connection.DeleteSetResponse
	(*AddToSetRequest)(nil),       // 5: connection.AddToSetRequest
	(*AddToSetResponse)(nil),      // 6: connection.AddToSetResponse
	(*RemoveFromSetRequest)(nil),  // 7: connection.RemoveFromSetRequest
	(*RemoveFromSetResponse)(nil), // 8: connection.RemoveFromSetResponse
}
var file_pkg_connection_pb_connection_proto_depIdxs = []int32{
	0, // 0: connection.GetSetRequest.set:type_name -> connection.SetInfo
	0, // 1: connection.DeleteSetRequest.set:type_name -> connection.SetInfo
	0, // 2: connection.AddToSetRequest.set:type_name -> connection.SetInfo
	0, // 3: connection.RemoveFromSetRequest.set:type_name -> connection.SetInfo
	1, // 4: connection.Connection.GetSet:input_type -> connection.GetSetRequest
	3, // 5: connection.Connection.DeleteSet:input_type -> connection.DeleteSetRequest
	5, // 6: connection.Connection.AddToSet:input_type -> connection.AddToSetRequest
	7, // 7: connection.Connection.RemoveFromSet:input_type -> connection.RemoveFromSetRequest
	2, // 8: connection.Connection.GetSet:output_type -> connection.GetSetResponse
	4, // 9: connection.Connection.DeleteSet:output_type -> connection.DeleteSetResponse
	6, // 10: connection.Connection.AddToSet:output_type -> connection.AddToSetResponse
	8, // 11: connection.Connection.RemoveFromSet:output_type -> connection.RemoveFromSetResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_connection_pb_connection_proto_init() }
func file_pkg_connection_pb_connection_proto_init() {
	if File_pkg_connection_pb_connection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_connection_pb_connection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_connection_pb_connection_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_connection_pb_connection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_connection_pb_connection_proto_goTypes,
		DependencyIndexes: file_pkg_connection_pb_connection_proto_depIdxs,
		MessageInfos:      file_pkg_connection_pb_connection_proto_msgTypes,
	}.Build()
	File_pkg_connection_pb_connection_proto = out.File
	file_pkg_connection_pb_connection_proto_rawDesc = nil
	file_pkg_connection_pb_connection_proto_goTypes = nil
	file_pkg_connection_pb_connection_proto_depIdxs = nil
}
